[tool.poetry]
name = "aaa-repo"
version = "0.1.0"
description = ""
authors = ["AdelheidVC <adelheidvc@freedom.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
